version: '3.7'

services:
  deepgram-proxy:
    container_name: ${PROXY_NAME}
    build: 
      context: ./deepgram-proxy
    volumes:
      - ./deepgram-proxy:/usr/src/app:rw
    ports:
      - ${PROXY_PORT}:8080
  deepgram-react:
    container_name: ${FRONTEND_NAME}
    build: 
      context: ./deepgram-react
    volumes:
      - ./deepgram-react:/usr/src/app:rw
    ports:
      - ${FRONTEND_PORT}:3000
    